fastlane_version "1.109.0"

generated_fastfile_id "c877c1c4-fb71-4400-af36-2da628cc2978"

default_platform :ios

platform :ios do
  before_all do
    cocoapods

  end

 desc "Runs all the tests"
 lane :test do
   scan(scheme: "BabylonHealthDemo")
   slather(
      output_directory: "coverage",
      workspace: "BabylonHealthDemo.xcworkspace",
      scheme: "BabylonHealthDemo",
      proj: "BabylonHealthDemo.xcodeproj",
      html: true
   )
   gym(
     # scheme: "BabylonHealthDemo"
   )
 end
end
